# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "app_camera_support"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "camera_web"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "js_qr"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "qrscan_flutter_web"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "qrscan_flutter_web_example"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
