name: tekartik_js_qr
description: Cozmo JsQR dart wrapper
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  meta:
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a

dev_dependencies:
  build_runner: '>=2.1.0'
  build_web_compilers: '>=3.2.0'
  build_test: '>=2.1.0'
  process_run:
  test:
