name: tekartik_js_qr
description: Cozmo JsQR dart wrapper
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  meta: ">=1.15.0"
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a

dev_dependencies:
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  build_test: '>=2.1.0'
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
