name: tekartik_js_qr
description: Cozmo JsQR dart wrapper
publish_to: none
version: 0.1.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta:
  js:
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: null_safety

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  build_test: '>=1.3.7'
  pedantic: ^1.8.0
  process_run:
  test:

dependency_overrides:
  # pedantic: '>=1.9.0'