name: qrscan_flutter_web_example
description: qrscan_flutter_web example
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  tekartik_qrscan_flutter_web:
    git:
      url: https://github.com/tekartik/app_camera.dart
      path: qrscan_flutter_web
      ref: dart3a
    version: '>=0.1.0'
  cupertino_icons: ">=1.0.8"

dev_dependencies:
  flutter_test:
    sdk: flutter
  dev_build: ">=1.1.2"
  tekartik_app_lints_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_lints
    version: '>=0.1.0'
dependency_overrides:
  tekartik_qrscan_flutter_web:
    path: ../qrscan_flutter_web
  tekartik_camera_web:
    path: ../camera_web
  tekartik_js_qr:
    path: ../js_qr
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # include js_qr javascript file
    - packages/tekartik_js_qr/js/js_qr.js
